name: JDK 17 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      
      - name: Call workflow
        uses: ./.github/workflows/maven.yml
        with:
         jdk_version: 17
