name: JDK 17 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    uses: yaphet17/Reusable-Workflows-POC/.github/workflows/maven.yml@${{github.ref}}
    with:
      jdk_version: 17
