name: JDK 8 Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        uses: ./.github/workflows/maven.yml
        with:
            jdk_version: 8
