name: Java CI with Maven

on:
  workflow_call:
    inputs:
      jdk_version:
        required: true
        type: number
        default: 8


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up multiple JDK 
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.jdk_version }}
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-reports
        path: |
          build/reports
